# -*- coding: utf-8 -*-
"""YOLOv8_Ghost_Lightweight_Fall_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRgTZVS78X59zkdC2KZJym3hUohhfIjD

---
## Step 1 — Environment Setup
"""

!pip install ultralytics -q

import torch
print(f"PyTorch : {torch.__version__}")
print(f"CUDA    : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU     : {torch.cuda.get_device_name(0)}")

from google.colab import drive
drive.mount('/content/drive')

# Export ONNX FP16 from existing best.pt (run this cell only if re-exporting)
from ultralytics import YOLO
import os

model = YOLO("/content/drive/MyDrive/fall_detection_ghostneck_results/best.pt")

# Export to ONNX FP16 — halves model size with negligible accuracy loss
fp16_path = model.export(format="onnx", imgsz=640, half=True)
size = os.path.getsize(fp16_path) / 1024**2
print(f"ONNX FP16 saved: {fp16_path} ({size:.2f} MB)")

# Copy to Google Drive for persistent storage
import shutil
shutil.copy(fp16_path, "/content/drive/MyDrive/fall_detection_ghostneck_results/best_fp16.onnx")
print("Saved to Drive.")

"""---
## Step 2 — Dataset Setup
"""

import os, zipfile, yaml
from pathlib import Path

# ============================================================
# CONFIG — same dataset as the baseline notebook
# ============================================================
DRIVE_ZIP   = "/content/drive/MyDrive/fall_detection.v1i.yolov8"
DATASET_DIR = "/content/dataset"
# ============================================================

# Locate dataset zip
zip_path = None
for candidate in [DRIVE_ZIP, DRIVE_ZIP + ".zip"]:
    if os.path.exists(candidate):
        zip_path = candidate
        break

if zip_path is None:
    print("Dataset not found. Files in Drive root containing 'fall':")
    for f in sorted(os.listdir("/content/drive/MyDrive/")):
        if "fall" in f.lower():
            print(f"  {f}  <-- possible match")
    raise FileNotFoundError("Update DRIVE_ZIP path above and re-run.")

# Extract if not already done
if not os.path.exists(DATASET_DIR):
    os.makedirs(DATASET_DIR, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(DATASET_DIR)
    print("Dataset extracted.")
else:
    print("Dataset directory already exists — skipping extraction.")

# Read class names from original Roboflow data.yaml
dataset_path     = Path(DATASET_DIR)
yaml_candidates  = list(dataset_path.rglob("data.yaml"))
if yaml_candidates:
    DATA_YAML = str(yaml_candidates[0])
    with open(DATA_YAML) as f:
        config = yaml.safe_load(f)
    print(f"\nFound config: {DATA_YAML}")
    print(f"Classes: {config.get('names')}")

# Rewrite data.yaml with absolute Colab paths
if (dataset_path / "train" / "images").exists():
    train_p = "train/images"
    val_p   = "valid/images" if (dataset_path / "valid").exists() else "val/images"
else:
    train_p, val_p = "images/train", "images/val"

nc    = config.get("nc", 3)
names = config.get("names", ["fall_detected", "sitting", "walking"])

new_cfg = {"path": str(dataset_path), "train": train_p, "val": val_p, "nc": nc, "names": names}
test_p  = "test/images" if (dataset_path / "test").exists() else ""
if test_p:
    new_cfg["test"] = test_p

FINAL_YAML = str(dataset_path / "data_colab.yaml")
with open(FINAL_YAML, 'w') as f:
    yaml.dump(new_cfg, f, default_flow_style=False, allow_unicode=True)
print(f"Config written: {FINAL_YAML}")

"""---
## Step 3 — Define GhostNeck-YOLOv8n Architecture

### Key design decision
The Backbone is kept identical to the original YOLOv8n so that COCO pretrained weights
can be loaded without modification. Only the Neck (FPN + PAN path) is replaced with
Ghost-based C3Ghost blocks, which halve Neck parameters via cheap depthwise feature generation.
"""

# Write the GhostNeck-YOLOv8n architecture YAML.
# nc is set to 80 here (COCO default) — Ultralytics overrides it at training time
# using the nc value in data_colab.yaml.
ghost_yaml_content = """
# GhostNeck-YOLOv8n
# Backbone: unchanged YOLOv8n (loads COCO pretrained weights)
# Neck: C2f replaced by C3Ghost; strided Conv replaced by GhostConv
# Reference: Han et al., GhostNet, CVPR 2020

nc: 80

scales:
  n: [0.33, 0.25, 1024]

# ----- Backbone (unchanged from YOLOv8n) -----
backbone:
  - [-1, 1, Conv, [64, 3, 2]]         # 0  P1/2
  - [-1, 1, Conv, [128, 3, 2]]        # 1  P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]        # 3  P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]        # 5  P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]       # 7  P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]          # 9

# ----- Neck + Head (Ghost modules) -----
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]  # 10  upsample P5 -> P4 scale
  - [[-1, 6], 1, Concat, [1]]                    # 11  concat with backbone P4
  - [-1, 3, C3Ghost, [512]]                       # 12  Ghost bottleneck (replaces C2f)

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]  # 13  upsample -> P3 scale
  - [[-1, 4], 1, Concat, [1]]                    # 14  concat with backbone P3
  - [-1, 3, C3Ghost, [256]]                       # 15  Ghost bottleneck (P3 output)

  - [-1, 1, GhostConv, [256, 3, 2]]              # 16  Ghost strided conv (downsample)
  - [[-1, 12], 1, Concat, [1]]                   # 17  concat with neck P4
  - [-1, 3, C3Ghost, [512]]                       # 18  Ghost bottleneck (P4 output)

  - [-1, 1, GhostConv, [512, 3, 2]]              # 19  Ghost strided conv (downsample)
  - [[-1, 9], 1, Concat, [1]]                    # 20  concat with backbone SPPF
  - [-1, 3, C3Ghost, [1024]]                      # 21  Ghost bottleneck (P5 output)

  - [[15, 18, 21], 1, Detect, [nc]]              # 22  detection head (P3, P4, P5)
"""

GHOST_YAML = "/content/yolov8n-ghostneck.yaml"
with open(GHOST_YAML, 'w') as f:
    f.write(ghost_yaml_content)

print(f"GhostNeck-YOLOv8n architecture YAML saved: {GHOST_YAML}")
print("Design: Backbone unchanged | Neck uses C3Ghost + GhostConv")

# Compare parameter counts: baseline vs GhostNeck
from ultralytics import YOLO
from ultralytics.utils.torch_utils import model_info

print("=" * 60)
print("Model Structure Comparison")
print("=" * 60)

# Baseline YOLOv8n
baseline_model = YOLO("yolov8n.yaml")
b_params = sum(p.numel() for p in baseline_model.model.parameters())
b_layers = len(list(baseline_model.model.modules()))
baseline_model.info(verbose=True)

print(f"\n[Baseline YOLOv8n]")
print(f"  Parameters: {b_params:,}")

# GhostNeck variant
ghost_model = YOLO(GHOST_YAML)
g_params = sum(p.numel() for p in ghost_model.model.parameters())
g_layers = len(list(ghost_model.model.modules()))
ghost_model.info(verbose=True)

print(f"\n[GhostNeck-YOLOv8n (Proposed)]")
print(f"  Parameters: {g_params:,}")

# Reduction summary
param_reduction = (1 - g_params / b_params) * 100
print(f"\n[Improvement]")
print(f"  Parameter reduction : {param_reduction:.1f}%")
print(f"  Baseline: {b_params/1e6:.2f}M  ->  GhostNeck: {g_params/1e6:.2f}M")

"""---
## Step 4 — Train GhostNeck-YOLOv8n

We initialise the GhostNeck model from COCO pretrained weights (yolov8n.pt).
Ultralytics loads weights for matching Backbone layers and randomly initialises
the modified Neck — this is intentional and expected.
"""

from ultralytics import YOLO

# Load GhostNeck architecture, initialised with COCO pretrained backbone weights
model = YOLO(GHOST_YAML).load("yolov8n.pt")
print("COCO pretrained weights loaded (backbone matched; neck randomly initialised).")

OUTPUT_DIR = "/content/runs"

results = model.train(
    data    = FINAL_YAML,
    epochs  = 100,
    imgsz   = 640,
    batch   = 16,
    project = OUTPUT_DIR,
    name    = "fall_detection_ghostneck",

    # Optimiser — identical to baseline for a fair comparison
    optimizer      = "SGD",
    lr0            = 0.01,
    lrf            = 0.01,
    momentum       = 0.937,
    weight_decay   = 0.0005,
    warmup_epochs  = 3.0,
    warmup_momentum= 0.8,

    # Augmentation — identical to baseline
    mosaic       = 1.0,
    mixup        = 0.1,
    copy_paste   = 0.0,
    close_mosaic = 10,
    fliplr       = 0.5,
    flipud       = 0.0,
    degrees      = 5.0,
    translate    = 0.1,
    scale        = 0.5,
    shear        = 2.0,
    perspective  = 0.0,
    hsv_h        = 0.015,
    hsv_s        = 0.7,
    hsv_v        = 0.4,
    erasing      = 0.0,

    patience = 20,
    seed     = 42,    # same seed as baseline for fair comparison
    workers  = 2,
    exist_ok = True,
    verbose  = True,
)

print("\n" + "=" * 40)
print("GhostNeck model training complete.")
print("=" * 40)

"""---
## Step 5 — Model Evaluation
"""

from IPython.display import Image, display

# Training curves
results_img = Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "results.png"
if results_img.exists():
    display(Image(filename=str(results_img), width=900))

# Confusion matrix
cm_img = Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "confusion_matrix.png"
if cm_img.exists():
    display(Image(filename=str(cm_img), width=600))

# Load best checkpoint and evaluate
best_path  = Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "weights" / "best.pt"
best_model = YOLO(str(best_path))

metrics    = best_model.val(data=FINAL_YAML)

p, r = metrics.box.mp, metrics.box.mr
f1   = 2 * p * r / (p + r) if (p + r) > 0 else 0
model_size = best_path.stat().st_size / (1024 * 1024)
total_ms   = sum(metrics.speed.values())

print("\n" + "=" * 55)
print("GhostNeck-YOLOv8n — Evaluation Results")
print("=" * 55)
print(f"  mAP@0.5       : {metrics.box.map50:.4f}")
print(f"  mAP@0.5:0.95  : {metrics.box.map:.4f}")
print(f"  Precision     : {p:.4f}")
print(f"  Recall        : {r:.4f}")
print(f"  F1 Score      : {f1:.4f}")
print(f"  Model size    : {model_size:.2f} MB")
print(f"  Latency       : {total_ms:.1f} ms")
print(f"  FPS           : {1000/total_ms:.1f}")

# Comparison with baseline
print("\n" + "=" * 55)
print("Baseline vs GhostNeck Comparison")
print("=" * 55)
print(f"  {'Metric':<20s} {'Baseline':>10s} {'GhostNeck':>10s} {'Delta':>10s}")
print(f"  {'─'*50}")

baseline = {
    'mAP@0.5': 0.9644, 'mAP@0.5:0.95': 0.7448,
    'Precision': 0.9845, 'Recall': 0.9476,
    'F1': 0.9657, 'Size(MB)': 5.97, 'FPS': 61.7
}
ghost_results = {
    'mAP@0.5': metrics.box.map50, 'mAP@0.5:0.95': metrics.box.map,
    'Precision': p, 'Recall': r,
    'F1': f1, 'Size(MB)': model_size, 'FPS': 1000/total_ms
}

for key in baseline:
    b_val = baseline[key]
    g_val = ghost_results[key]
    if key == 'Size(MB)':
        change = f"{(1 - g_val/b_val)*100:+.1f}%"
    elif key == 'FPS':
        change = f"{(g_val/b_val - 1)*100:+.1f}%"
    else:
        change = f"{(g_val - b_val):+.4f}"
    print(f"  {key:<20s} {b_val:>10.4f} {g_val:>10.4f} {change:>10s}")

"""---
## Step 6 — Model Quantization and Export
"""

import time
import numpy as np

print("=" * 55)
print("Model Quantization Export")
print("=" * 55)

quantization_results = {}

# 1. ONNX FP32
print("\n[1/3] Exporting ONNX FP32 ...")
onnx_path = best_model.export(format="onnx", imgsz=640, simplify=True)
onnx_size = os.path.getsize(onnx_path) / (1024*1024)
quantization_results['ONNX (FP32)'] = {'size': onnx_size, 'path': onnx_path}
print(f"  Size: {onnx_size:.2f} MB")

# 2. ONNX FP16 — halves model size; recommended format for Raspberry Pi via NCNN
print("\n[2/3] Exporting ONNX FP16 ...")
onnx_fp16_path = best_model.export(format="onnx", imgsz=640, simplify=True, half=True)
onnx_fp16_size = os.path.getsize(onnx_fp16_path) / (1024*1024)
quantization_results['ONNX (FP16)'] = {'size': onnx_fp16_size, 'path': onnx_fp16_path}
print(f"  Size: {onnx_fp16_size:.2f} MB")

# 3. TensorRT FP16
print("\n[3/3] Exporting TensorRT FP16 ...")
try:
    engine_path = best_model.export(format="engine", imgsz=640, half=True)
    engine_size = os.path.getsize(engine_path) / (1024*1024)
    quantization_results['TensorRT (FP16)'] = {'size': engine_size, 'path': engine_path}
    print(f"  Size: {engine_size:.2f} MB")
except Exception as e:
    print(f"  TensorRT export failed (Colab may not support it): {e}")
    print(f"  This does not affect the experiment — TensorRT conversion can be done on Jetson.")

# Quantization summary
print("\n" + "=" * 55)
print("Quantization Summary")
print("=" * 55)
print(f"  {'Format':<20s} {'Size (MB)':>10s} {'Ratio':>10s}")
print(f"  {'─'*40}")
print(f"  {'PyTorch FP32':<20s} {model_size:>10.2f} {'1.0x':>10s}")
for name, info in quantization_results.items():
    ratio = f"{model_size/info['size']:.1f}x"
    print(f"  {name:<20s} {info['size']:>10.2f} {ratio:>10s}")

# Verify ONNX FP32 accuracy — should be within ~0.002 mAP of PyTorch
print("\nValidating ONNX FP32 accuracy ...")
onnx_model   = YOLO(quantization_results['ONNX (FP32)']['path'])
onnx_metrics = onnx_model.val(data=FINAL_YAML)

print(f"\n  ONNX FP32 mAP@0.5 : {onnx_metrics.box.map50:.4f}")
print(f"  PyTorch   mAP@0.5 : {metrics.box.map50:.4f}")
print(f"  Difference         : {(onnx_metrics.box.map50 - metrics.box.map50):+.4f}")

"""---
## Step 7 — Results Summary and Save to Drive
"""

print("\n" + "=" * 70)
print("Paper Results Table")
print("=" * 70)
print(f"\n{'Model':<25s} {'Params':>10s} {'Size(MB)':>10s} {'mAP@0.5':>10s} {'mAP@50:95':>10s} {'FPS':>8s}")
print(f"{'─'*73}")

# Baseline
print(f"{'YOLOv8n (Baseline)':<25s} {'3.16M':>10s} {'5.97':>10s} {'0.9644':>10s} {'0.7448':>10s} {'61.7':>8s}")

# GhostNeck
ghost_params = f"{g_params/1e6:.2f}M"
print(f"{'GhostNeck-YOLOv8n (Ours)':<25s} {ghost_params:>10s} {model_size:>10.2f} {metrics.box.map50:>10.4f} {metrics.box.map:>10.4f} {1000/total_ms:>8.1f}")

# GhostNeck + FP16
if 'ONNX (FP16)' in quantization_results:
    fp16_size = quantization_results['ONNX (FP16)']['size']
    print(f"{'GhostNeck + FP16':<25s} {ghost_params:>10s} {fp16_size:>10.2f} {'~same':>10s} {'~same':>10s} {'TBD':>8s}")

# GhostNeck + TensorRT
if 'TensorRT (FP16)' in quantization_results:
    trt_size = quantization_results['TensorRT (FP16)']['size']
    print(f"{'GhostNeck + TRT':<25s} {ghost_params:>10s} {trt_size:>10.2f} {'TBD':>10s} {'TBD':>10s} {'TBD':>8s}")

print(f"\nNote: TBD = To Be Determined (requires edge device benchmarking)")
print(f"      FPS figures for Baseline and GhostNeck are measured on Colab T4 GPU.")

# Save all results to Google Drive
import shutil

SAVE_DIR = "/content/drive/MyDrive/fall_detection_ghostneck_results"
os.makedirs(SAVE_DIR, exist_ok=True)

files = {
    "best.pt"              : Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "weights" / "best.pt",
    "last.pt"              : Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "weights" / "last.pt",
    "results.png"          : Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "results.png",
    "confusion_matrix.png" : Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "confusion_matrix.png",
    "args.yaml"            : Path(OUTPUT_DIR) / "fall_detection_ghostneck" / "args.yaml",
    "yolov8n-ghostneck.yaml": Path(GHOST_YAML),
}

# Add quantized exports
for name, info in quantization_results.items():
    ext         = Path(info['path']).suffix
    files[f"best{ext}"] = Path(info['path'])

print(f"\nSaving to: {SAVE_DIR}")
for name, src in files.items():
    if Path(src).exists():
        shutil.copy2(str(src), os.path.join(SAVE_DIR, name))
        size = os.path.getsize(os.path.join(SAVE_DIR, name)) / 1024 / 1024
        print(f"  Saved: {name:35s} ({size:.2f} MB)")

# Save experiment report
report = f"""# GhostNeck-YOLOv8n Lightweight Fall Detection — Experiment Report

## Model Design
- Base model       : YOLOv8n
- Modification     : C2f modules in Neck replaced with C3Ghost blocks; strided Conv replaced with GhostConv
- Baseline params  : {b_params:,}
- GhostNeck params : {g_params:,}
- Parameter reduction: {param_reduction:.1f}%

## Baseline vs GhostNeck Comparison
| Metric        | Baseline | GhostNeck | Delta   |
|---------------|----------|-----------|---------|
| mAP@0.5       | 0.9644   | {metrics.box.map50:.4f}    | {metrics.box.map50-0.9644:+.4f} |
| mAP@0.5:0.95  | 0.7448   | {metrics.box.map:.4f}    | {metrics.box.map-0.7448:+.4f} |
| Precision     | 0.9845   | {p:.4f}    | {p-0.9845:+.4f} |
| Recall        | 0.9476   | {r:.4f}    | {r-0.9476:+.4f} |
| F1            | 0.9657   | {f1:.4f}    | {f1-0.9657:+.4f} |
| Model size    | 5.97 MB  | {model_size:.2f} MB   | {(1-model_size/5.97)*100:.1f}% reduction |
| FPS (T4)      | 61.7     | {1000/total_ms:.1f}      | {(1000/total_ms/61.7-1)*100:+.1f}% |

## Quantization Results
| Format        | Size    |
|---------------|---------|
| PyTorch FP32  | {model_size:.2f} MB |
"""
for name, info in quantization_results.items():
    report += f"| {name} | {info['size']:.2f} MB |\n"

with open(os.path.join(SAVE_DIR, "experiment_report.md"), 'w') as f:
    f.write(report)

print(f"\nAll results saved to Google Drive.")
