# -*- coding: utf-8 -*-
"""YOLOv8_Fall_Detection_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15976QsuvaJAECFGy8v-7Yl_F0SPVPZjY

# YOLOv8 Elderly Fall Detection — Training Pipeline

**Dataset**: University of Strathclyde Fall Detection (Roboflow, YOLOv8 format)
**Model**: YOLOv8n (nano — suitable for edge device deployment)
**Augmentation**: Online data augmentation optimised for indoor fall scenarios

---

## Before You Start
1. Upload the dataset zip `fall_detection.v1i.yolov8` to your Google Drive root
2. In Colab, select **Runtime → Change runtime type → T4 GPU**
3. Run each cell top to bottom

---
## Step 1 — Environment Setup
"""

# Install dependencies
!pip install ultralytics -q

# Verify GPU availability
import torch
print(f"PyTorch version : {torch.__version__}")
print(f"CUDA available  : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU             : {torch.cuda.get_device_name(0)}")
    print(f"VRAM            : {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")
else:
    print("WARNING: No GPU detected. Go to Runtime > Change runtime type and select GPU.")

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

print("\nGoogle Drive mounted at /content/drive/MyDrive/")

"""---
## Step 2 — Extract Dataset
"""

import os
import zipfile
from pathlib import Path

# ============================================================
# CONFIG — update DRIVE_ZIP if your filename differs
# ============================================================
DRIVE_ZIP   = "/content/drive/MyDrive/fall_detection.v1i.yolov8"  # dataset zip in Drive
DATASET_DIR = "/content/dataset"                                    # extraction target
# ============================================================

# Auto-detect zip file (supports both .zip and no-extension Roboflow exports)
zip_path = None
for candidate in [DRIVE_ZIP, DRIVE_ZIP + ".zip", DRIVE_ZIP + ".tar.gz"]:
    if os.path.exists(candidate):
        zip_path = candidate
        break

if zip_path is None:
    # List Drive root to help locate the file
    print("Dataset file not found. Please check the filename and path.")
    print("\nFiles in Google Drive root:")
    for f in sorted(os.listdir("/content/drive/MyDrive/")):
        if "le2i" in f.lower() or "fall" in f.lower() or "yolo" in f.lower():
            print(f"  {f}  <-- possible match")
        else:
            print(f"  {f}")
    raise FileNotFoundError("Update the DRIVE_ZIP path above and re-run.")

print(f"Found dataset : {zip_path}")
print(f"File size     : {os.path.getsize(zip_path) / 1024 / 1024:.1f} MB")

# Extract dataset
if os.path.exists(DATASET_DIR):
    print(f"\nDataset directory already exists — skipping extraction.")
else:
    print(f"\nExtracting to {DATASET_DIR} ...")
    os.makedirs(DATASET_DIR, exist_ok=True)

    if zip_path.endswith(".zip") or not zip_path.endswith(".tar.gz"):
        try:
            with zipfile.ZipFile(zip_path, 'r') as zf:
                zf.extractall(DATASET_DIR)
            print("Extraction complete (ZIP).")
        except zipfile.BadZipFile:
            # File may be tar.gz without the correct extension
            import tarfile
            with tarfile.open(zip_path, 'r:gz') as tf:
                tf.extractall(DATASET_DIR)
            print("Extraction complete (TAR.GZ).")
    else:
        import tarfile
        with tarfile.open(zip_path, 'r:gz') as tf:
            tf.extractall(DATASET_DIR)
        print("Extraction complete (TAR.GZ).")

# Print directory structure for verification
print(f"\nDataset directory structure:")
for root, dirs, files in os.walk(DATASET_DIR):
    level = root.replace(DATASET_DIR, '').count(os.sep)
    indent = '  ' * level
    subdir = os.path.basename(root)
    file_count = len(files)
    if level <= 2:
        print(f"{indent}{subdir}/ ({file_count} files)")
    if level > 2:
        break

"""---
## Step 3 — Dataset Inspection and Statistics
"""

import yaml
from collections import Counter

# Auto-locate data.yaml
yaml_candidates = list(Path(DATASET_DIR).rglob("data.yaml"))
if not yaml_candidates:
    yaml_candidates = list(Path(DATASET_DIR).rglob("*.yaml"))

if yaml_candidates:
    DATA_YAML = str(yaml_candidates[0])
    print(f"Found config file: {DATA_YAML}")
    with open(DATA_YAML, 'r') as f:
        config = yaml.safe_load(f)
    print(f"Contents:\n{yaml.dump(config, allow_unicode=True)}")
else:
    print("data.yaml not found — will be generated in the next step.")
    DATA_YAML = None

# Count sample distribution per split
print("=" * 55)
print("Dataset Sample Statistics")
print("=" * 55)

total_fall   = 0
total_normal = 0
total_images = 0

for split in ["train", "valid", "val", "test"]:
    # Support both directory layouts
    img_dirs = [
        Path(DATASET_DIR) / split / "images",
        Path(DATASET_DIR) / "images" / split,
    ]
    label_dirs = [
        Path(DATASET_DIR) / split / "labels",
        Path(DATASET_DIR) / "labels" / split,
    ]

    img_dir   = next((d for d in img_dirs   if d.exists()), None)
    label_dir = next((d for d in label_dirs if d.exists()), None)

    if not img_dir or not label_dir:
        continue

    imgs   = list(img_dir.glob("*.jpg")) + list(img_dir.glob("*.png"))
    n_imgs = len(imgs)

    fall   = 0
    normal = 0
    for lbl in label_dir.glob("*.txt"):
        with open(lbl) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) >= 5:
                    cls = int(parts[0])
                    if cls == 0:
                        fall += 1
                    else:
                        normal += 1

    total_fall   += fall
    total_normal += normal
    total_images += n_imgs

    print(f"\n  [{split:>5s}]  images: {n_imgs:>5d}  |  fall: {fall:>5d}  |  normal: {normal:>5d}")

print(f"\n  {'─' * 50}")
print(f"  [total]  images: {total_images:>5d}  |  fall: {total_fall:>5d}  |  normal: {total_normal:>5d}")

if total_fall > 0:
    ratio = total_normal / total_fall
    print(f"\n  normal:fall = {ratio:.1f}:1", end="")
    if ratio > 3:
        print("  WARNING: imbalanced — data augmentation will help mitigate this.")
    else:
        print("  Class ratio is acceptable.")

# Visualise sample images to verify annotations
import cv2
import matplotlib.pyplot as plt
import numpy as np
import random

def draw_yolo_bbox(img, label_path, class_names=["fall_detected", "sitting", "walking"],
                   colors=[(0, 0, 255), (0, 200, 0), (255, 165, 0)]):
    """Draw YOLO-format bounding boxes on an image."""
    h, w = img.shape[:2]
    if not os.path.exists(label_path):
        return img
    with open(label_path) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) < 5:
                continue
            cls = int(parts[0])
            xc, yc, bw, bh = [float(x) for x in parts[1:5]]
            x1 = int((xc - bw / 2) * w)
            y1 = int((yc - bh / 2) * h)
            x2 = int((xc + bw / 2) * w)
            y2 = int((yc + bh / 2) * h)
            color = colors[cls] if cls < len(colors) else (255, 255, 0)
            label = class_names[cls] if cls < len(class_names) else f"cls_{cls}"
            cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
            cv2.putText(img, label, (x1, y1 - 8),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)
    return img

# Locate training images
train_img_dir = None
for candidate in [Path(DATASET_DIR)/"train"/"images", Path(DATASET_DIR)/"images"/"train"]:
    if candidate.exists():
        train_img_dir = candidate
        break

if train_img_dir:
    all_imgs = list(train_img_dir.glob("*.jpg")) + list(train_img_dir.glob("*.png"))
    samples  = random.sample(all_imgs, min(8, len(all_imgs)))

    fig, axes = plt.subplots(2, 4, figsize=(20, 10))
    fig.suptitle("Training set samples (red=fall_detected, green=sitting, orange=walking)", fontsize=16)

    for ax, img_path in zip(axes.flat, samples):
        img = cv2.imread(str(img_path))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        label_path = str(img_path).replace("/images/", "/labels/")
        label_path = label_path.rsplit(".", 1)[0] + ".txt"
        img = draw_yolo_bbox(img, label_path)
        ax.imshow(img)
        ax.set_title(img_path.name, fontsize=8)
        ax.axis("off")

    for ax in axes.flat[len(samples):]:
        ax.axis("off")

    plt.tight_layout()
    plt.show()
else:
    print("Training image directory not found.")

"""---
## Step 4 — Fix data.yaml Paths

Roboflow exports use relative or local paths — we rewrite them as absolute Colab paths.
"""

# Generate a Colab-compatible data.yaml
dataset_path = Path(DATASET_DIR)

# Auto-detect directory layout
if (dataset_path / "train" / "images").exists():
    train_path = "train/images"
    val_path   = "valid/images" if (dataset_path / "valid").exists() else "val/images"
    test_path  = "test/images"  if (dataset_path / "test").exists()  else ""
else:
    train_path = "images/train"
    val_path   = "images/val"
    test_path  = "images/test" if (dataset_path / "images" / "test").exists() else ""

# Read class names from original Roboflow yaml
nc    = 3
names = ["fall_detected", "sitting", "walking"]
if DATA_YAML and os.path.exists(DATA_YAML):
    with open(DATA_YAML) as f:
        orig = yaml.safe_load(f)
    if "nc"    in orig: nc    = orig["nc"]
    if "names" in orig: names = orig["names"]

# Write new data.yaml with absolute paths
new_config = {
    "path"  : str(dataset_path),
    "train" : train_path,
    "val"   : val_path,
    "nc"    : nc,
    "names" : names,
}
if test_path:
    new_config["test"] = test_path

FINAL_YAML = str(dataset_path / "data_colab.yaml")
with open(FINAL_YAML, 'w') as f:
    yaml.dump(new_config, f, default_flow_style=False, allow_unicode=True)

print(f"Colab-compatible config written to: {FINAL_YAML}")
print(f"\nContents:")
with open(FINAL_YAML) as f:
    print(f.read())

"""---
## Step 5 — Train YOLOv8n Baseline

### Augmentation strategy

| Parameter     | Value | Rationale                                              |
|---------------|-------|--------------------------------------------------------|
| mosaic        | 1.0   | 4-image mosaic — increases scene diversity             |
| mixup         | 0.1   | Blends two images — improves generalisation            |
| fliplr        | 0.5   | Horizontal flip — falls are direction-agnostic         |
| flipud        | 0.0   | No vertical flip — indoor cameras don't invert         |
| degrees       | 5.0   | Slight rotation — simulates tilted cameras             |
| hsv_v         | 0.4   | Brightness variation — simulates day/night lighting    |
| perspective   | 0.0   | No perspective warp — preserves human body proportions |
| close_mosaic  | 10    | Disable mosaic in final 10 epochs for stable convergence|
"""

from ultralytics import YOLO

# ============================================================
# TRAINING CONFIG — adjust for quick tests (e.g. epochs=10)
# ============================================================
MODEL_NAME = "yolov8n.pt"   # COCO pretrained weights (nano variant)
EPOCHS     = 100
BATCH_SIZE = 16             # safe for T4 (14 GB VRAM)
IMG_SIZE   = 640
OUTPUT_DIR = "/content/runs"
# ============================================================

# Load YOLOv8n with COCO pretrained weights (transfer learning)
model = YOLO(MODEL_NAME)

# Start training
results = model.train(
    data    = FINAL_YAML,
    epochs  = EPOCHS,
    imgsz   = IMG_SIZE,
    batch   = BATCH_SIZE,
    project = OUTPUT_DIR,
    name    = "fall_detection",

    # Optimiser
    optimizer      = "SGD",
    lr0            = 0.01,    # initial learning rate
    lrf            = 0.01,    # final lr = lr0 * lrf
    momentum       = 0.937,
    weight_decay   = 0.0005,
    warmup_epochs  = 3.0,     # linear warmup for 3 epochs
    warmup_momentum= 0.8,

    # Mosaic / MixUp augmentation
    mosaic       = 1.0,   # 4-image mosaic probability
    mixup        = 0.1,   # MixUp blend probability
    copy_paste   = 0.0,   # copy-paste disabled
    close_mosaic = 10,    # disable mosaic in last 10 epochs

    # Geometric augmentation
    fliplr      = 0.5,    # horizontal flip probability
    flipud      = 0.0,    # vertical flip disabled (indoor setting)
    degrees     = 5.0,    # rotation +/-5 deg
    translate   = 0.1,    # translation +/-10%
    scale       = 0.5,    # scale +/-50%
    shear       = 2.0,    # shear +/-2 deg
    perspective = 0.0,    # perspective disabled (preserves body proportions)

    # Colour augmentation
    hsv_h = 0.015,  # hue variation
    hsv_s = 0.7,    # saturation variation
    hsv_v = 0.4,    # brightness variation (day/night simulation)

    # Misc
    erasing  = 0.0,   # random erasing disabled
    patience = 20,    # early stopping: halt if no improvement for 20 epochs
    seed     = 42,    # fixed seed for reproducibility
    workers  = 2,     # Colab recommended
    exist_ok = True,
    verbose  = True,
)

print("\n" + "=" * 40)
print("Training complete.")
print("=" * 40)

"""---
## Step 6 — View Training Results
"""

from IPython.display import Image, display

# Training curves
results_img = Path(OUTPUT_DIR) / "fall_detection" / "results.png"
if results_img.exists():
    display(Image(filename=str(results_img), width=900))
else:
    print(f"Training curve not found: {results_img}")

# Confusion matrix
cm_img = Path(OUTPUT_DIR) / "fall_detection" / "confusion_matrix.png"
if cm_img.exists():
    display(Image(filename=str(cm_img), width=600))
else:
    print("Confusion matrix not found.")

# Validation batch prediction visualisation
val_imgs = sorted(Path(OUTPUT_DIR, "fall_detection").glob("val_batch*_pred.jpg"))
for img_path in val_imgs[:3]:
    print(f"\n{img_path.name}")
    display(Image(filename=str(img_path), width=800))

"""---
## Step 7 — Model Evaluation (Detailed Metrics)
"""

# Load best checkpoint
best_model_path = Path(OUTPUT_DIR) / "fall_detection" / "weights" / "best.pt"
best_model = YOLO(str(best_model_path))

# Run validation on the held-out validation set
metrics = best_model.val(data=FINAL_YAML)

print("\n" + "=" * 50)
print("Baseline YOLOv8n — Validation Results")
print("=" * 50)
print(f"  mAP@0.5       : {metrics.box.map50:.4f}")
print(f"  mAP@0.5:0.95  : {metrics.box.map:.4f}")
print(f"  Precision     : {metrics.box.mp:.4f}")
print(f"  Recall        : {metrics.box.mr:.4f}")

p, r = metrics.box.mp, metrics.box.mr
f1   = 2 * p * r / (p + r) if (p + r) > 0 else 0
print(f"  F1 Score      : {f1:.4f}")

model_size = best_model_path.stat().st_size / (1024 * 1024)
print(f"\n  Model size    : {model_size:.2f} MB")

print(f"\n  Inference speed (GPU):")
print(f"    Preprocess  : {metrics.speed['preprocess']:.1f} ms")
print(f"    Inference   : {metrics.speed['inference']:.1f} ms")
print(f"    Postprocess : {metrics.speed['postprocess']:.1f} ms")
total_ms = sum(metrics.speed.values())
print(f"    Total       : {total_ms:.1f} ms  ({1000/total_ms:.1f} FPS)")

"""---
## Step 8 — Export Model for Edge Deployment
"""

# Export to ONNX (universal intermediate format)
onnx_path = best_model.export(format="onnx", imgsz=640, simplify=True)
print(f"\nONNX model exported: {onnx_path}")
print(f"  Size: {os.path.getsize(onnx_path) / 1024 / 1024:.2f} MB")

print(f"\nDeployment options:")
print(f"  Jetson (TensorRT)  : copy ONNX to Jetson, convert with trtexec")
print(f"  Raspberry Pi (NCNN): convert ONNX to .param + .bin using ncnn toolchain")
print(f"  Intel (OpenVINO)   : mo --input_model best.onnx")

"""---
## Step 9 — Save Results to Google Drive
"""

import shutil

SAVE_DIR = "/content/drive/MyDrive/fall_detection_results"
os.makedirs(SAVE_DIR, exist_ok=True)

# Files to save
files_to_save = {
    "best.pt"              : Path(OUTPUT_DIR) / "fall_detection" / "weights" / "best.pt",
    "last.pt"              : Path(OUTPUT_DIR) / "fall_detection" / "weights" / "last.pt",
    "results.png"          : Path(OUTPUT_DIR) / "fall_detection" / "results.png",
    "confusion_matrix.png" : Path(OUTPUT_DIR) / "fall_detection" / "confusion_matrix.png",
    "args.yaml"            : Path(OUTPUT_DIR) / "fall_detection" / "args.yaml",
}

# Include ONNX export
onnx_files = list(Path(OUTPUT_DIR).rglob("*.onnx"))
if onnx_files:
    files_to_save["best.onnx"] = onnx_files[0]

print(f"Saving to Google Drive: {SAVE_DIR}")
print("-" * 50)

for name, src in files_to_save.items():
    if src.exists():
        dst  = os.path.join(SAVE_DIR, name)
        shutil.copy2(str(src), dst)
        size = os.path.getsize(dst) / 1024 / 1024
        print(f"  Saved: {name:30s} ({size:.2f} MB)")
    else:
        print(f"  Not found: {name}")

# Save experiment report
report = f"""# Fall Detection Experiment Report

## Dataset
- University of Strathclyde Fall Detection (Roboflow, YOLOv8 format)
- Total images : {total_images}
- Fall labels  : {total_fall}
- Normal labels: {total_normal}

## Model
- Architecture  : YOLOv8n (nano)
- Pretrained    : COCO
- Input size    : {IMG_SIZE}x{IMG_SIZE}
- Model size    : {model_size:.2f} MB

## Evaluation Results
- mAP@0.5      : {metrics.box.map50:.4f}
- mAP@0.5:0.95 : {metrics.box.map:.4f}
- Precision    : {p:.4f}
- Recall       : {r:.4f}
- F1 Score     : {f1:.4f}

## Inference Speed (Colab T4 GPU)
- Total latency : {total_ms:.1f} ms
- FPS           : {1000/total_ms:.1f}

## Training Config
- Epochs     : {EPOCHS}
- Batch size : {BATCH_SIZE}
- Optimiser  : SGD (lr=0.01)
- Early stop : patience=20

## Augmentation
- Mosaic      : 1.0
- MixUp       : 0.1
- Horizontal flip : 0.5
- Rotation    : +/-5 deg
- HSV (h=0.015, s=0.7, v=0.4)
"""

with open(os.path.join(SAVE_DIR, "experiment_report.md"), 'w', encoding='utf-8') as f:
    f.write(report)
print(f"  Saved: experiment_report.md")

print(f"\nAll results saved to Google Drive.")
print(f"  Path: {SAVE_DIR}")

"""---
## Step 10 — Quick Inference Test (Optional)

Run the trained model on a few test images.
"""

# Find test or validation images
test_img_dir = None
for candidate in [
    Path(DATASET_DIR) / "test"  / "images",
    Path(DATASET_DIR) / "valid" / "images",
    Path(DATASET_DIR) / "images" / "test",
    Path(DATASET_DIR) / "images" / "val",
]:
    if candidate.exists():
        test_img_dir = candidate
        break

if test_img_dir:
    test_imgs = list(test_img_dir.glob("*.jpg")) + list(test_img_dir.glob("*.png"))
    samples   = random.sample(test_imgs, min(4, len(test_imgs)))

    results = best_model.predict(
        source   = [str(p) for p in samples],
        conf     = 0.5,
        save     = True,
        project  = OUTPUT_DIR,
        name     = "predict_samples",
        exist_ok = True,
    )

    # Display prediction results
    pred_dir  = Path(OUTPUT_DIR) / "predict_samples"
    pred_imgs = sorted(pred_dir.glob("*.jpg"))[:4]

    if pred_imgs:
        fig, axes = plt.subplots(1, len(pred_imgs), figsize=(5*len(pred_imgs), 5))
        if len(pred_imgs) == 1:
            axes = [axes]
        for ax, img_path in zip(axes, pred_imgs):
            img = cv2.imread(str(img_path))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            ax.imshow(img)
            ax.axis("off")
        plt.suptitle("Model Prediction Results", fontsize=14)
        plt.tight_layout()
        plt.show()

    # Print per-detection output
    for r in results:
        boxes = r.boxes
        if len(boxes) > 0:
            for box in boxes:
                cls  = int(box.cls)
                conf = float(box.conf)
                name = r.names[cls]
                print(f"  Detected: {name} (confidence: {conf:.2f})")
        else:
            print(f"  No objects detected.")
else:
    print("Test image directory not found.")

"""---

## Experiment Checklist

After completing all steps, you should have:

- [x] Trained model weights (`best.pt`)
- [x] ONNX export (`best.onnx`)
- [x] Training curves (`results.png`) — for paper figures
- [x] Confusion matrix (`confusion_matrix.png`) — for paper figures
- [x] Evaluation metrics (mAP, Precision, Recall, F1) — for paper tables
- [x] Inference speed (ms, FPS) — for paper tables
- [x] Model size (MB) — for paper tables
- [x] Full experiment report (`experiment_report.md`)

All files are saved to the `fall_detection_results` folder in Google Drive.
"""
